### ISSUE TITLE
Not working with Xcode 9.2

### ISSUE THREAD

**Issue by trispo** [ShawnBaek/Custom-UIKit-NavigationBar#1]
Hi,
the example does not work with Xcode 9.2 for me. Any suggestions?

**Comment by ShawnBaek** [comment]
Hi 👋 

I will check and reply this weekend 

Thanks



나의 iPhone에서 보냄

2018. 1. 5. 오후 7:34, trispo <notifications@github.com> 작성:

**Comment by orta** [comment]
I took a look and shipped a PR #2

**Comment by ShawnBaek** [comment]
@orta Thank you so much!
